export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ACCOUNT_ROUTE = '/account'
export const SHOP_ROUTE = '/'
export const ORDERS_ROUTE = '/myorders'
export const BASKET_ROUTE = '/basket'
export const FLOWER_ROUTE = '/flower'